all: msg1 msg2 msg3 msg4 msg5

msg1: msg1.c
	gcc -g -O0 -o msg1 msg1.c

msg2: msg2.c
	gcc -g -O0 -o msg2 msg2.c

msg3: msg3.c
	gcc -g -O0 -o msg3 msg3.c

msg4: msg4.c
	gcc -g -O0 -o msg4 msg4.c


msg5: msg5.c
	gcc -g -O0 -o msg5 msg5.c

clean:
	rm -rf *.o msg1 msg2 msg3 msg4 msg5 
