all: pid_example pid_example1

pid_example: pid_example.c
	gcc -g -O0 -o pid_example pid_example.c

pid_example1: pid_example1.c
	gcc -g -O0 -o pid_example1 pid_example1.c

clean:
	rm -rf *.o pid_example pid_example1
