all: wait1 wait2 wait3 wait4 wait5

wait1: wait1.c
	gcc -g -O0 -o wait1 wait1.c

wait2: wait2.c
	gcc -g -O0 -o wait2 wait2.c

wait3: wait3.c
	gcc -g -O0 -o wait3 wait3.c

wait4: wait4.c
	gcc -g -O0 -o wait4 wait4.c

wait5: wait5.c
	gcc -g -O0 -o wait5 wait5.c

clean:
	rm -rf *.o wait1 wait2 wait3 wait4 wait5
